language: node_js
node_js:
  - '8.1.3'

before_script:
  - npm install -g firebase-tools
  - npm install
  - npm i npm@latest -g

script:
  - npm run build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

cache:
  directories:
    - $HOME/.npm
